openapi: 3.0.0
info:
  title: 
  version: 1.0.0
  description: Movies API

tags:
  - name: Showtimes
    description: Endpoints related to showtimes

paths:
  /api/showtimes/:
    get:
      tags:
        - Showtimes
      summary: Get all showtimes
      responses:
        '200':
          description: A list of showtimes
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      tags:
        - Showtimes
      summary: Create a showtime, only admins can do this
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movieId:
                  type: string
                  description: The id of the movie
                showDate:
                  type: string
                  description: The date of the showtime
                showTime:
                  type: string
                  description: The time of the showtime
                screenNumber:
                  type: integer
                  description: The screen number of the showtime
                availableSeats:
                  type: integer
                  description: The available seats of the showtime
      responses:
        '201':
          description: Showtime created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/showtimes/{showtimeId}:
    get:
      tags:
        - Showtimes
      summary: Get a showtime by id
      parameters:
        - name: showtimeId
          in: path
          required: true
          description: The id of the showtime
          schema:
            type: string
      responses:
        '200':
          description: A showtime
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Showtimes
      summary: Delete a showtime, only admins can do this
      parameters:
        - name: showtimeId
          in: path
          required: true
          description: The id of the showtime
  /api/showtimes/movie/{movieId}:
    get:
      tags:
        - Showtimes
      summary: Get all showtimes for a movie
      parameters:
        - name: movieId
          in: path
          required: true
          description: The id of the movie
          schema:
            type: string
      responses:
        '200':
          description: A list of showtimes
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/showtimes/upcoming/{movieId}:
    get:
      tags:
        - Showtimes
      summary: Get all upcoming showtimes for a movie
      parameters:
        - name: movieId
          in: path
          required: true
          description: The id of the movie
          schema:
            type: string
      responses:
        '200':
          description: A list of showtimes
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
