openapi: 3.0.0
info:
  title: 
  version: 1.0.0
  description: Movies API

tags:
  - name: Halls
    description: Endpoints related to halls

paths:
  /api/halls:
    get:
      tags:
        - Halls
      summary: Get all halls
      responses:
        '200':
          description: A list of halls
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: array
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
    post:
      tags:
        - Halls
      summary: Create a hall
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the hall
                total_rows:
                  type: integer
                  description: The total number of rows in the hall
                seats_per_row:
                  type: integer
                  description: The total number of seats per row in the hall
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
  /api/halls/{hallId}:
    get:
      tags:
        - Halls
      summary: Get a hall by ID
      parameters:
        - name: hallId
          in: path
          required: true
          description: The ID of the hall
          schema:
            type: string
      responses:
        '200':
          description: A hall
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Halls
      summary: Update a hall by ID
      parameters:
        - name: hallId
          in: path
          required: true
          description: The ID of the hall
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the hall
                total_rows:
                  type: integer
                  description: The total number of rows in the hall
                seats_per_row:
                  type: integer
                  description: The total number of seats per row in the hall
      responses:
        '200':
          description: Hall updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Halls
      summary: Delete a hall by ID
      parameters:
        - name: hallId
          in: path
          required: true
          description: The ID of the hall
          schema:
            type: string
      responses:
        '200':
          description: Hall deleted
          content:
            application/json:
              schema:
                type: object
                properties: