openapi: 3.0.0
info:
  title: Movies
  version: 1.0.0
  description: Movies API

tags:
  - name: Movies
    description: Endpoints related to movies

paths:
  /api/movies:
    get:
      tags:
        - Movies
      summary: Get all movies
      responses:
        '200':
          description: A list of movies
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      tags:
        - Movies
      summary: Create a movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the movie
                genre:
                  type: string
                  description: The genre of the movie
                duration:
                  type: integer
                  description: The duration of the movie in minutes
                rating:
                  type: number
                  description: The rating of the movie
                release_date:
                  type: string
                  format: date
                  description: The release date of the movie
                description:
                  type: string
                  description: The description of the movie
      responses:
        '201':
          description: A movie
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/movies/{id}:
    get:
      tags:
        - Movies
      summary: Get a movie by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the movie
          schema:
            type: integer
      responses:
        '200':
          description: A movie
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Movies
      summary: Delete a movie by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the movie
          schema:
            type: integer
      responses:
        '200':
          description: A movie
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error