openapi: 3.0.0
info:
  title: 
  version: 1.0.0
  description: Movies API

tags:
  - name: Seats
    description: Endpoints related to seats

paths:
  /api/seats/{seatId}:
    get:
      tags:
        - Seats
      summary: Get a seat by ID
      parameters:
        - name: seatId
          in: path
          required: true
          description: The ID of the seat
          schema:
            type: string
      responses:
        '200':
          description: A seat
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Seats
      summary: Update a seat by ID
      parameters:
        - name: seatId
          in: path
          required: true
          description: The ID of the seat
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: The status of the seat
      responses:
        '200':
          description: Seat updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/seats/showtime/{showtimeId}:
    get:
      tags:
        - Seats
      summary: Get all seats of a showtime
      parameters:
        - name: showtimeId
          in: path
          required: true
          description: The ID of the showtime
          schema:
            type: string
      responses:
        '200':
          description: A list of seats
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/availability/{seatId}:
    get:
      tags:
        - Seats
      summary: Get the availability of a seat
      parameters:
        - name: seatId
          in: path
          required: true
          description: The ID of the seat
          schema:
            type: string
      responses:
        '200':
          description: The availability of the seat
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error