openapi: 3.0.0
info:
  title: 
  version: 1.0.0
  description: Movies API

tags:
  - name: Payments
    description: Endpoints related to payments

paths:
  /api/payments/:
    get:
      tags:
        - Payments
      summary: Get all payments
      responses:
        '200':
          description: A list of payments
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      tags:
        - Payments
      summary: Create a payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reservationId:
                  type: array
                  description: The ID of the reservation to pay for
                  example: [1]
                amount:
                  type: number
                  description: The amount to pay
                  example: 10.0
      responses:
        '201':
          description: Payment created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/payments/{paymentId}:
    get:
      tags:
        - Payments
      summary: Get a payment by ID
      parameters:
        - name: paymentId
          in: path
          required: true
          description: The ID of the payment to get
          schema:
            type: integer
      responses:
        '200':
          description: Payment found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Payments
      summary: Delete a payment by ID
      parameters:
        - name: paymentId
          in: path
          required: true
          description: The ID of the payment to delete
          schema:
            type: integer
      responses:
        '204':
          description: Payment deleted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/payments/{paymentId}/reservations:
    get:
      tags:
        - Payments
      summary: Get all reservations for a payment
      parameters:
        - name: paymentId
          in: path
          required: true
          description: The ID of the payment to get reservations for
          schema:
            type: integer
      responses:
        '200':
          description: A list of reservations
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error