openapi: 3.0.0
info:
  title: 
  version: 1.0.0
  description: Movies API

tags:
  - name: Reservations
    description: Endpoints related to reservations

paths:
  /api/reservations/:
    get:
      tags:
        - Reservations
      summary: Get all reservations
      responses:
        '200':
          description: A list of reservations
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      tags:
        - Reservations
      summary: Create a reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                showtimeId:
                  type: integer
                  description: The ID of the showtime
                seatNumbers:
                  type: array
                  description: The number of seats to reserve
      responses:
        '201':
          description: Reservation created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/reservations/{reservationId}:
    get:
      tags:
        - Reservations
      summary: Get a reservation
      parameters:
        - name: reservationId
          in: path
          required: true
          description: The ID of the reservation
          schema:
            type: integer
      responses:
        '200':
          description: A reservation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put: 
      tags:
        - Reservations
      summary: Update a reservation status
      parameters:
        - name: reservationId
          in: path
          required: true
          description: The ID of the reservation
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: status change 
      responses:
        '200':
          description: Reservation updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Reservations
      summary: Delete a reservation
      parameters:
        - name: reservationId
          in: path
          required: true
          description: The ID of the reservation
          schema:
            type: integer
      responses:
        '200':
          description: Reservation deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/reservations/user/{userId}:
    get:
      tags:
        - Reservations
      summary: Get all reservations of a user
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: A list of reservations
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/reservations/showtime/{showtimeId}:
    get:
      tags:
        - Reservations
      summary: Get all reservations of a showtime
      parameters:
        - name: showtimeId
          in: path
          required: true
          description: The ID of the showtime
          schema:
            type: integer
      responses:
        '200':
          description: A list of reservations
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/reservations/check-availability/{showtimeId}:
    get:
      tags:
        - Reservations
      summary: Check availability of a showtime
      parameters:
        - name: showtimeId
          in: path
          required: true
          description: The ID of the showtime
          schema:
            type: integer
        - name: seatNumber
          in: query
          required: true
          description: The seat number
          schema:
            type: integer
      responses:
        '200':
          description: A list of available seats
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/reservations/count/{showtimeId}:
    get:
      tags:
        - Reservations
      summary: Get the number of reservations for a showtime
      parameters:
        - name: showtimeId
          in: path
          required: true
          description: The ID of the showtime
          schema:
            type: integer
      responses:
        '200':
          description: The number of reservations
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the response
                  data:
                    type: object
                    description: The data of the response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error